### ISSUE TITLE
Cannot find any definition

### ISSUE THREAD

**Issue by Ruddy2007** [SimonSimCity/Xamarin-CrossDownloadManager#11]
Does this work anymore? There is no sample code to look at and following the guide you have I cannot get it working. I just get errors as it cannot find anything inside the plugin. 

I can init the plugin for IOS and Android but cannot use it after. 

`var downloadManager = CrossDownloadManager.Instance;`

Instance is not defined within CrossDownloadManager. Is this a problem with the plugin or am I doing something wrong in the setup. Would be great to get this working, looks very useful. 

Cheers.

**Comment by SimonSimCity** [comment]
Oh, I'm sorry ... I meant `CrossDownloadManager.Current` - not `CrossDownloadManager.Instance`. I'll change it right away.

**Comment by Ruddy2007** [comment]
Ah makes sense, I just looked into it and found it. Cheers.

**Comment by Ruddy2007** [comment]
@SimonSimCity  Also

`var file = downloadManager.CreateDownloadFile (url);`

should be

`var file = downloadManager.CreateDownloadFile (url, null);`

by default as it accepts headers as a second param?

**Comment by SimonSimCity** [comment]
I have to provide a proper default there. The system currently only accepts a `new Dictionary<string, string>()` as second parameter and it seems to crash if you provide `null` there.
