### ISSUE TITLE
How to set Cookie if server wants session.

### ISSUE THREAD

**Issue by ashishkumawat** [SimonSimCity/Xamarin-CrossDownloadManager#110]
To help us fix your issue, please provide the information in the below template. 

> Note: If you want to save time, please create a fork, reproduce the bug in the sample projects and add a link to the repository here.

### Steps to reproduce

1.

2.

3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Platform:** 
- [ ] iOS
- [ ] Android
- [ ] UWP
- [ ] Other

**Device:** 
- [ ] Simulator
- [ ] Real device (please specify)

**Comment by SimonSimCity** [comment]
Well, you can set headers on an `IDownloadFile` implementation, which allows you to send cookies. If you need more help, please get familiar with HTTP headers and which options they give you.

**Comment by ashishkumawat** [comment]
Thank I will try
