### ISSUE TITLE
Unable to download and parse m3u8 type files.

### ISSUE THREAD

**Issue by Azhy-Slemany** [SimonSimCity/Xamarin-CrossDownloadManager#116]
> Hi there, this plugin is great but why it can't download and parse m3u8 file types as a video extension, it just downloads as a m3u8 text file and it can't parse it, so please can you add these extensions to your plugin.

### Expected behavior
It should parse m3u8 files to a video extension and then download it.

### Actual behavior
It just downloads the m3u8 text file instead the video parts in the text file.

### Configuration

**Platform:** 
- [x] iOS
- [x] Android

**Device:** 
- [x] Simulator
- [x] Real device (Samsung Galaxy s4(I9505))

**Comment by SimonSimCity** [comment]
Well, this is all logic which you have to fit on top of it. The sore purpose of this library is to define a unified interface for downloading files. What you do with the files is all yours. You can (of course) write some logic that parses the m3u8 file and adds the individual files to the queue.
