### ISSUE TITLE
How to know Download is completed ?

### ISSUE THREAD

**Issue by Nagendra574** [SimonSimCity/Xamarin-CrossDownloadManager#119]
please let me know How can I recognize the download file is completely downloaded or not. Is there any event is a fire. I am using Xamarin forms with MVVM 

Thanks in advance.

**Comment by SimonSimCity** [comment]
A look into the sample implementation (https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/tree/develop/Sample) should give you the hint how to do it.

You only need to wait for the status of the file to switch to `completed` (https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/Droid/MainActivity.cs#L102)
