### ISSUE TITLE
Add a sample project

### ISSUE THREAD

**Issue by SimonSimCity** [SimonSimCity/Xamarin-CrossDownloadManager#12]
As suggested by @Ruddy2007, we need a project where we show a sample implementation and maybe some extended features, that are hard to describe in code.

**Comment by Ruddy2007** [comment]
@SimonSimCity I was working on a demo for this but I can't even seem to get it working at the moment. Not sure what I'm doing wrong, if you get around to making a simple project please could you let me know so I can take a look. Cheers.

**Comment by carlosgtzrdz** [comment]
Me too.... any sample?

**Comment by Ruddy2007** [comment]
@carlosgtzrdz Im still working on it but no luck. Can't get the download to start up, really can't find why yet. Seems to be a pretty simple idea but no luck.

**Comment by Ruddy2007** [comment]
Also @SimonSimCity you changed `UriForDownloadedFile` to `PathNameForDownloadedFile`. That need's to be changed on the front page too.

**Comment by SimonSimCity** [comment]
@Ruddy2007, @carlosgtzrdz I've added a sample implementation.

Please check it out (https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/tree/master/Sample) and tell me what I've missed out in the manual.

If you have time, feel free to improve this sample.

**Comment by carlosgtzrdz** [comment]
@SimonSimCity  I got it working... thnx dude! very clean!

**Comment by Ruddy2007** [comment]
@SimonSimCity Cheers for the sample, going to take a look now. Just one think, when I opened the sample it didn't have the plugin in the packages. Shouldn't this be in there and just restore when opened? (just an idea).

Will let you know if I run into any problems, cheers again.

**Comment by SimonSimCity** [comment]
@Ruddy2007 The sample project doesn't link the packages from nuget, that's right. But that's done because I want to compile the sample project against the actual development-projects, that are in the same solution. Those should be linked to the projects.

**Comment by SimonSimCity** [comment]
@Ruddy2007, I've tested the sample project and can confirm that the Android version failed. I guess I forgot to clean the project before compiling again.

Please check out the version I've uploaded now - that works for me after cleaning every cache I could find. I've also added some comments that should help you avoid some pitfalls.

If you only want to see the changes I did to the project, see here: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/commit/ebcf1a591429d7282e7eb448ded6de83f883de97#diff-c5dd1b2697720fe692c529688d3f4f8d

**Comment by Ruddy2007** [comment]
@SimonSimCity Cheers. I have been working on the IOS one and I have it working now. Works pretty well, just trying to get my head around how to update the UI on my application when downloading (moving views etc). Thanks for your work on this, sample has helped loads.
