### ISSUE TITLE
Random PAUSED - WAITING TO RETRY

### ISSUE THREAD

**Issue by shakazulu89** [SimonSimCity/Xamarin-CrossDownloadManager#127]
Hey and thank you for this library.

Has anyone come across this issue where downloads on android (both emulator and real device, both small and large files, can happen either at the start of file download or in middle of transfer for example when bytes were already written) seem to randomly hit a "PAUSED - WAITING TO RETRY" status before the downloader tries to continue the download and then it finishes?

I appreciate any feedback and sorry for not using the template!

Thanks
Roy

**Comment by SimonSimCity** [comment]
Can you please answer some questions on this?

* Does this happen with the sample app as well?
* Does this only happen on Android, have you tested the other platforms?
* Is the download always reported as finished right after resuming, even if there are bytes left?
* Is the network you're connected to stable?

**Comment by shakazulu89** [comment]
- I will try with sample app tomorrow

- I don't have apple devices to try on iOS

- it continues the download where it left off I'm pretty sure. Will confirm tomorrow

- yes I have a solid network.

**Comment by shakazulu89** [comment]
i havent tried the sample app yet but i did try to use different files to make sure it hasnt to do with my server and the issues is still happening when i try to use this link for downloading:
https://file-examples-com.github.io/uploads/2017/10/file-example_PDF_1MB.pdf

and i did confirm it simply pauses randomly somewhere in the download and then continues after 20 seconds or so...

any ideas what might be causing this?

**Comment by shakazulu89** [comment]
update: i tried the sample app using the file i sent in my previous comment and same thing is happening. not always, but after clicking download 3 times the downloader went into "Paused.WaitingToRetry". 

i was also thinking what would be the best way to make the downloader immediately retry to download again instead of waiting around 30 seconds before retrying... ?

i would really appreciate any help because this is a big issue fir me. 

Thanks

**Comment by shakazulu89** [comment]
it seems to only happen on the emulator. i remember checking on device and it happened but now i cant recreate it so i will close this ticket ...

**Comment by SimonSimCity** [comment]
I didn't have much time until now to test this, and haven't heard of others having this issue. Feel free to request a re-opening as you see it appearing again.

Seems to be another issue which might be solved by implementing a custom download manager for Android #34

**Comment by nziosys** [comment]
I'm facing a similer issue. Only on simulator and randomly the download pauses about 99% or less, than retries and fails.
