### ISSUE TITLE
Xamarin dependency requirement issue with MAUI

### ISSUE THREAD

**Issue by SunshineSpring666** [SimonSimCity/Xamarin-CrossDownloadManager#132]
Hi Simon,
    I tried to make it run with MAUI, the next version of Xamarin. It seems that the Xamarin dependency requirement is blocking the App from running.
    I've seen other 3rd-party xamarin nuget packages run normally in a MAUI project. So I'm wondering if you could remove the Xamarin dependency requirement or pack another package like this, so that this wonderful library could provide its functionality in MAUI?
    Many thanks.

    Best regards

**Comment by SimonSimCity** [comment]
Hey, I have to say that my interest has shifted away from app development with Xamarin. If anyone has the time, your contribution is always welcome!

In case you want me to do it, this might take some time until I go back on this project again. After all, I was just doing this in my free time. It would be different if someone would pay me for the job...

**Comment by SunshineSpring666** [comment]
I see. Thanks for your reply.
