### ISSUE TITLE
[Android] Automatically request permission

### ISSUE THREAD

**Issue by jamesmontemagno** [SimonSimCity/Xamarin-CrossDownloadManager#20]
You could follow the practice I have done here:
https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Media/Media/Media.Plugin.Android/MediaImplementation.cs#L147-L163

Or simply link people to my permissions plugin to handle and request the permission before attempting to start a download.

**Comment by SimonSimCity** [comment]
I named it in the manual, so the users themselves can decide how to handle it.

**Comment by jamesmontemagno** [comment]
Perfect :) thanks

**Comment by large** [comment]
Link changed to: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaImplementation.cs

Check out RequestStoragePermission() function
