### ISSUE TITLE
[Android] CurrentActivity plugin to remove Init

### ISSUE THREAD

**Issue by jamesmontemagno** [SimonSimCity/Xamarin-CrossDownloadManager#21]
If you happen to use the permission plugin or if you don't you can rely on the Current Activity plugin: https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/CurrentActivity to grab the current activity that is visible. This would do away with the Init() call.

**Comment by SimonSimCity** [comment]
@jamesmontemagno, do you know if there is a way to reduce the code the user has to add for a life-cycle? I have to initialize it in some way ... before I just called the Init() method on the activity, but I guess the solution I now have is a bit cleaner, isn't it?

**Comment by SimonSimCity** [comment]
By the latest changes, I got it so far, that I just needed the current activity to initialize a service. Today I found out, that this equally can be done by the static property on `Application.Context`, so I dropped the dependency again.

Thanks for your hint. Now the user skips to call that `init()` method and still has all the service.
