### ISSUE TITLE
The type or namespace name IDownloadFile couldn't be found

### ISSUE THREAD

**Issue by jamal-deen** [SimonSimCity/Xamarin-CrossDownloadManager#36]
I have run the [sample](https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/tree/master/Sample) project successfully. In my project I am going to download a file from `URL`, So I have planned to use your `NuGet plugin`.
I have pasted the `Downloader.cs` file from sample project to my project. It shows this error `the type or namespace name IDownloadFile couldn't be found(are you missing a using directive or assembly reference)`
in this line `public IDownloadFile File;`
And also I am getting this error too that the name `CrossDownloadManager doesn't exist in the current context`.
I have added the `NuGet `plugin `Xam.Plugin.DownloadManager v 1.0.0.1`, I have checked the package references under `Xam.plugin.Downloadmanager.Abstractions` it has only `IDownloadManager `there is no `interface` with the name called `IDownloadFile`

**Comment by SimonSimCity** [comment]
@jamal-deen I don't fully understand the versioning you write about here.

You wrote, that you've added the nuget package in version 1.0.0.1 - but there's no version out here that has reached the 1.x state. I have published a `0.10.0` version lately, that's right (https://www.nuget.org/packages/Xam.Plugins.DownloadManager/).

All classes within this package are located at the namespace `Plugin.DownloadManager` - and I see the `Plugin.DownloadManager.Abstractions.IDownloadFile` interface in my assembly-browser for the latest version.

Can you please specify exactly what you've done? Maybe you have a project where you need to add `Xam.Plugin.DownloadManager` as a new reference? Keep in mind that you have to add it to every project you want to access this plugin.

**Comment by jamal-deen** [comment]
I have used this `NuGet` plugin https://www.nuget.org/packages/Xam.Plugin.DownloadManager/  instead of using your's https://www.nuget.org/packages/Xam.Plugins.DownloadManager/ . just now I have removed the previous plugin and added your's. I will let you know once I have done.

**Comment by SimonSimCity** [comment]
Thanks. I'll close this issue for now. If you have any other questions, please open a new issue.

**Comment by jamal-deen** [comment]
Thanks lot you.
