### ISSUE TITLE
I already got the output now problem is that where is my locally saved file l I am unclear about answer thatyou have given below?  ?

### ISSUE THREAD

**Issue by samirgc** [SimonSimCity/Xamarin-CrossDownloadManager#42]

**Comment by SimonSimCity** [comment]
Please take a look at the sample-project. It contains all the info you need - both for Android and for iOS.

If you want a dynamic location:
* https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/Droid/MainActivity.cs#L101
* https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/iOS/ExtendedUrlSessionDownloadDelegate.cs#L34

Or - if you provide a location on forehand:
* https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/Droid/MainActivity.cs#L18
* https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/iOS/ViewController.cs#L23
