### ISSUE TITLE
DownloadFileStatus.FAILED set based on got data, not on HTTP response code

### ISSUE THREAD

**Issue by sirantd** [SimonSimCity/Xamarin-CrossDownloadManager#43]
Some big players (like Amazon S3) provide extra info in body instead of file data (if you haven't permissions to download it).

#curl --head https://innapeace.s3-accelerate.amazonaws.com/servicesother_etcwfysgxv/6.mp3
HTTP/1.1 403 Forbidden
Content-Type: application/xml
Connection: keep-alive
x-amz-request-id: ED72D5E33707E497
x-amz-id-2: mkC6lBnZLeAm8mLv4DBWINT30z+6Ty3fDhlIvxQu4iuq0x6vql2fz6ouLlHIFFiSGrjOt1+g31g=
Date: Wed, 15 Mar 2017 16:43:07 GMT
Server: AmazonS3
X-Edge-O1-RID: XVh7nn6OgUkb5K7p68AhlSaaDzEM4M8--y6Gk1RbZTCioby4Gc3KeQ==
X-Cache: Error from cloudfront
Via: 1.1 200aa211a8ea240d0ebad1d696d1e1e0.cloudfront.net (CloudFront)
X-Amz-Cf-Id: fYMYovo3vL2CzI9VKuahUyRqQBCJvbZHigah0I-6TIJSql4yGmld9A==

As you can see, I have status code Forbidden, but if I open it in browser (or try to download with your plugin) - I'll have a text:

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>ED16DA5D01BCAFC1</RequestId><HostId>fEnvJvc/ordu/ZMPeUb8xXhdejf2nt8IxBgqZgWa/P2DS4icAZiqp1tWO50kemr1XDpNhjffGl8=</HostId></Error>

In this case plugin thinking that all ok and file was downloaded (because it got some data), and because you setting DetailedStatus only if DownloadFileStatus.FAILED I haven't chance to check HTTP status code (DetailedStatus will be always null).

It's possible to use expectedBytes as workaround (it will 0 for files without permissions), but plugin isn't update expectedBytes in background, so it isn't possible to check.

**Comment by SimonSimCity** [comment]
This could well be a problem platform dependent problem - maybe also related to it's version. Please tell me which platform and version of it you're experiencing this with. If you've tested multiple, please list them all.

**Comment by sirantd** [comment]
Thanks for your comment.

I've checked and there really different behaviours on IOS and Android:

IOS (10.2, 10.1, 9.3) - when I trying to download file which return HTTP 403 status (mentioned in initial post) download manager returns Status = DownloadFileStatus.COMPLETED and StatusDetails = null

Android (API 24) - when I trying to download same file - download manager returns Status = DownloadFileStatus.FAILED (what is better than in IOS), but StatusDetails = null

I think it should be same on IOS and Adnroid and at least return Status = DownloadFileStatus.FAILED

What do you think ?

**Comment by SimonSimCity** [comment]
The behavior on iOS you mentioned is not as expected. It's related to https://github.com/cocos2d/cocos2d-x/pull/14683 and I got it solved by the same fix.

For Android, it sounds like you have an old version. The demo provides me with the status-details `Error.HttpCode: 403` - but doesn't return the response-body. I've updated the iOS version to do the same.

Please add `https://www.myget.org/F/simonsimcity/api/v2` as new nuget-feed to your project and try the latest build of the CrossDownloadManager. The latest build should be `1.1.0-unstable0003`. Is the bug fixed in the new version?

**Comment by sirantd** [comment]
Thank you for bug-fix.

Seems now all ok, I've tested on IOS 9.3, 10.1, 10.2 and now get DownloadFileStatus.FAILED as I should on file with wrong permissions.

Unfortunately I still have null in StatusDetails, but will check my code.
