### ISSUE TITLE
PathName

### ISSUE THREAD

**Issue by SrCristian** [SimonSimCity/Xamarin-CrossDownloadManager#48]
How can I find the path and name of the file?

**Comment by SimonSimCity** [comment]
You either set it or it's downloaded to a temporary storage, as written in https://github.com/SimonSimCity/Xamarin-CrossDownloadManager#where-are-the-files-stored

The sample in https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/tree/develop/Sample let's the system save the file in the temporary storage.

Does this answer your request?

**Comment by SimonSimCity** [comment]
I guess it did ...
