### ISSUE TITLE
How to use without MvvmCross

### ISSUE THREAD

**Issue by JoshuaNovak919** [SimonSimCity/Xamarin-CrossDownloadManager#5]
How do I use this without MvvmCross?

**Comment by SimonSimCity** [comment]
The part of the documentation about MvvmCross is only if you are using MvvmCross and want to register it within the service-container there.

If you are not using MvvmCross, simply ignore the code there. Maybe I should add "(optional)" to the headline there ...

**Comment by JoshuaNovak919** [comment]
I figured that much, but the next block of code does not work without MvvmCross, so I figured there was a different way.

```
var downloadManager = CrossDownloadManager.Instance;
var file = downloadManager.CreateDownloadFile(url);
downloadManager.Start(file);
```

There is no `CrossDownloadManager.Instance` if you don't use MvvmCross.

**Comment by SimonSimCity** [comment]
It is. Just make sure you include the namespace `Plugin.DownloadManager`.

If you're using a system, where you have shared code, please make sure this library is included in the shared project as well as in the platform-specific projects.

**Comment by SimonSimCity** [comment]
@JoshuaNovak919, if the last message didn't help you, please reopen this issue.
