### ISSUE TITLE
[Android] Option to not show notification

### ISSUE THREAD

**Issue by leoalvaleo** [SimonSimCity/Xamarin-CrossDownloadManager#52]
Hi there!

I would like to know if there is an option for not showing the notification on Android.
I need to download a video from a URL and the status of the download should all be inside my app. Something like Netflix, Udemy, Spotify (for audio), etc. Where the content of the downloaded file cannot be  used outside my app.

Thanks in advance!

**Comment by SimonSimCity** [comment]
I was quite busy the last month, but I'll have a look at it now. Currently there's no possibility, but I'll open up for something ...

**Comment by SimonSimCity** [comment]
Does #56 answer your request?

**Comment by SimonSimCity** [comment]
Since there is no feedback in quite a while now, I'll merge my PR and close this.
