### ISSUE TITLE
Latest version 1.2.0 not available as Nuget

### ISSUE THREAD

**Issue by rsavutiu** [SimonSimCity/Xamarin-CrossDownloadManager#53]
Hi there,

Apparently the latest version is only available here, but has not made its way to Nuget Package Manager.

Between 1.1.1 and 1.2.0 it seems you have fixed callbacks on Android not being received properly (I would receive PENDING -> RUNNING and never completed) and only (5% of the totalbyteswritten callback).

Is there any way to add the source code to the Nuget Package Manager?

**Comment by SimonSimCity** [comment]
@rsavutiu You can just download the repository and add the projects to the specific platforms you want to use it on. But I see, that the auto-deployment script failed - which is quite sad ...

I'll take some time today to get a VM ready where I can create the nuget-file.

**Comment by SimonSimCity** [comment]
Thanks for waiting, I got my windows-machine back up and working 😃 

https://www.nuget.org/packages/Xam.Plugins.DownloadManager/1.2.0
