### ISSUE TITLE
Bait and Switch not working on latest VS2017 for Mac

### ISSUE THREAD

**Issue by WarBorg** [SimonSimCity/Xamarin-CrossDownloadManager#58]
hello,

I have just update the visual studio 2017 for mac to the latest version (7.1 build 1297) today and I am keep getting this error when trying to use the CrossDownloadManager.Current

> System.NotImplementedException has been thrown
> This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

this worked ok in the past but now I see it is not anymore, any ideas ?

**Comment by SimonSimCity** [comment]
@WarBorg Thanks for the feedback. I'm on the same build version of Visual Studio for Mac (community edition) and do not have the problem. Please try to check out this project and run the sample project. Does it work there?

I can remember also having had this problem and it worked again after cleaning up the project (remove`bin` and `obj` folders).

**Comment by WarBorg** [comment]
@SimonSimCity hey, I will try tomorrow the sample and see, I tried the clearing of all bin and obj folders and clean rebuild but running into the same issue, the thing is our application is modularised and we use separate iOS Libraries (and Android Libraries) as modules each with their own PCL Library. The DownloadManager is used only in one of the modules, and I am thinking the wrong DLL is being copied to the main project wich is set as startup, I will test more tomorrow and give feedback

**Comment by SimonSimCity** [comment]
@WarBorg Have you had some time to look at it? I wasn't able to reproduce it ...

**Comment by WarBorg** [comment]
@SimonSimCity sorry was really busy with work, the thing is the visual studio version is not the culprit since I tried it on an older version on a colegues mac and had the same issue, I will try to test the coming days , cheers

**Comment by SimonSimCity** [comment]
@WarBorg did you get this problem solved?

**Comment by WarBorg** [comment]
@SimonSimCity apperently everything works OK now but I have no ideea if I did something or something changed after updating some Microsoft product, if I will encounter the problem again I will let you know, as I mentioned in a previous post it is a very complex project and have no idea if somebody changed something that impacted the bait and switch procedure or not

**Comment by SimonSimCity** [comment]
Ok, so I'll close it for now.
