### ISSUE TITLE
URL in the downloadManager.Queue is missing when calling abort

### ISSUE THREAD

**Issue by TheMiao** [SimonSimCity/Xamarin-CrossDownloadManager#59]
I've using file= downloadManager.CreateDownloadFile(url); at beginning of the downloadfile.

When I call downloadManager.Abort(file); the url is missing in the IDownloadFile.

Will anyone have a look it and maybe fix it?

**Comment by SimonSimCity** [comment]
What platform do you have this problem on? I can confirm it working on Android and iOS.

If it fails on one of these platforms, please check out this repository and run the sample. If it fails there as well, please include as much information about your development environment as possible.
