### ISSUE TITLE
Changing visibility of notifications on Android

### ISSUE THREAD

**Issue by mhBahrami** [SimonSimCity/Xamarin-CrossDownloadManager#61]
I think, today, there is no option for changing notifications visibility for Android or iOS. I wanna make download's notification hidden on Android.

By adding the following code 

> `request.SetNotificationVisibility(DownloadVisibility.Hidden);`

to `StartDownload(DownloadManager, string, bool)` in `DownloadFileImplementation.cs` of `Plugin.DownloadManager.Android`, it would be done easily. 
 
Can you add this capability to `CrossDownloadManager`?

**Comment by SimonSimCity** [comment]
Does this PR answer your request? https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/pull/56

**Comment by mhBahrami** [comment]
Yeah. That's exactly what I need. Great job!
