### ISSUE TITLE
why i can not create LBIZZ folder and saved image in that folder ? 

### ISSUE THREAD

**Issue by 9409215070** [SimonSimCity/Xamarin-CrossDownloadManager#62]
CrossDownloadManager.Current.PathNameForDownloadedFile = new Func<IDownloadFile, string>(file =>
              {
                  string fileName = (new NSUrl(file.Url, false)).LastPathComponent;
                  Console.WriteLine("filename", fileName);
                  //var documents =Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                  //var directoryname = Path.Combine(documents, "LBIZZ");
                  //Directory.CreateDirectory(directoryname);
  
  
                  var documents1 = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                  var library = Path.Combine(documents1, "..", "Library");
                  var directoryname1 = Path.Combine(library, "LBIZZ");
                  Directory.CreateDirectory(directoryname1);
  
                  return Path.Combine(directoryname1, fileName);
              });
i am  creating  directory and Make LBIZZ Folder but in simulator doesn't make any folder so how to create folder and save image in that folder please help me?

**Comment by SimonSimCity** [comment]
@9409215070 What platform do you use to test it? If Android, please check that you have the permissions required.

**Comment by 9409215070** [comment]
CrossDownloadManager.Current.PathNameForDownloadedFile = new Func<IDownloadFile, string>
                (file =>
            {
                var documentsDirectory = Android.OS.Environment.ExternalStorageDirectory.AbsolutePath;
                //string folderName = "LBIZZ";
                var pathString = System.IO.Path.Combine(documentsDirectory, "DownloadImages");
                if (!System.IO.Directory.Exists(pathString))
                      System.IO.Directory.CreateDirectory(pathString);

                string fileName = Android.Net.Uri.Parse(file.Url).Path.Split('/').Last();
                pathString = System.IO.Path.Combine(pathString, fileName);
                Console.WriteLine("Path to my file: {0}\n", pathString);

                if (!System.IO.File.Exists(pathString))
                {
                    using (System.IO.FileStream fs = System.IO.File.Create(pathString))
                    {
                         Android.Net.Uri.Parse(file.Url).Path.Split('/').Last();
                    }
                }
                else
                {
                    Console.WriteLine("File \"{0}\" already exists.", fileName);
       
                }

                return pathString;
            });
in android I have successful created with above code But in IOS I don't know How to Create Directory  and save image in that folder ? please help Thanks In advance

**Comment by SimonSimCity** [comment]
Sorry, but I don't have the time to check this currently ... in addition, this is out of the scope of this project. https://github.com/dsplaisted/PCLStorage might be a resource that could help you ...
