### ISSUE TITLE
UWP: Queue doesn't get updated straight away.

### ISSUE THREAD

**Issue by BtrJay** [SimonSimCity/Xamarin-CrossDownloadManager#63]
Hi @SimonSimCity ,

I've installed the latest plugin on my project (1.2.0) and found an issue on UWP.

The steps to replicate is
1) start downloading a file in UWP
2) check Queue object
3) the file hasn't been added to download queue straight away

            CrossDownloadManager.Current.Start (File, mobileNetworkAllowed);
            var queue = CrossDownloadManager.Current.Queue;     //This is set to 0

I've checked the latest develop branch has got the fix for that but not sure if it was included in the latest nuget.

By the way, do you have a myget for this plugin so that I can test the latest build?

Kind Regards,

Jay Sim

**Comment by BtrJay** [comment]
Hi @SimonSimCity ,

Could you please advise us regarding the issue above? 

Kind Regards,

Jay

**Comment by SimonSimCity** [comment]
Thanks for getting again back to me on this issue. I was about to release a new version soon. Sadly, the automatic build stopped working and I haven't had the time to fix it - that's why there isn't a build available on myget ...

**Comment by BtrJay** [comment]
@SimonSimCity 

Thank you for that.

Please let me know when you publish the new version. (Hopefully soon)

Kind Regards,

Jay

**Comment by SimonSimCity** [comment]
A new version has just been released 🎉
