### ISSUE TITLE
[Android] Cancel button on Notification does not change file status to DownloadFileStatus.CANCELED

### ISSUE THREAD

**Issue by pratikarya** [SimonSimCity/Xamarin-CrossDownloadManager#64]

**Comment by SimonSimCity** [comment]
@pratikarya please tell me what you use that you have a cancel button on your application ... Haven't seen that before.

**Comment by pratikarya** [comment]
![screenshot_20170910-132406](https://user-images.githubusercontent.com/13135404/30251600-afa4667c-9680-11e7-99eb-fa19fef5ee2f.png)

I followed the example given in the sample project to download files using CrossDownloadManager.Current.StartDownload(file). 

I was showing a loading sign while the download was in progress. Once, the download was completed, I used to hide the loading sign. Now, when I click the cancel button (in the notification tray), the download stops, but the Status property of the file doesn't change (I need this to hide the loading sign).

I might have been mistaken, over here, as this might be related to the Android's DownloadManager. I need to figure out a way to get the event when cancel button (in the notification tray) is clicked.

if (args.PropertyName == "Status")
                {
                    switch (((IDownloadFile)sender).Status)
                    {
                        case DownloadFileStatus.FAILED:
                            //IsDownloading sets the visibility of the loading sign.
                            IsDownloading = false;
                            if (FailAction != null)
                                FailAction();
                            break;

                        case DownloadFileStatus.CANCELED:
                            CrossDownloadManager.Current.Abort(dfile);
                            IsDownloading = false;
                            break;

                        case DownloadFileStatus.COMPLETED:
                            if (_queue.Any() && _queue.Peek() == CurrentItem)
                                _queue.Dequeue();

                            if (_queue.Any())
                                StartDownload(_queue.Peek());
                            else
                                IsDownloading = false;

                            break;
                    }
                }

**Comment by SimonSimCity** [comment]
Would've been nice to notice that you're using Android 7.1.1 ...

There is no event. I've now added some code that assumes that a download was canceled if it isn't in the native download manager of Android anymore.

Can you check this code and verify if it works? https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/pull/66

**Comment by pratikarya** [comment]
Yes, should've mentioned the android version. 

I tried the updated code, the issue still exists. Even on canceling from the notification tray, the 'Status' of the file remains 'RUNNING'. This could be because UpdateFileProperties never sets the 'Status' to 'CANCELED'.

**Comment by SimonSimCity** [comment]
@pratikarya can you please check that you are having the changes I've added in #66? I haven't released a new version yet, neither have I merged into develop.

**Comment by pratikarya** [comment]
Yes, my bad, should've added a new comment, instead of editing the existing one.

**Comment by SimonSimCity** [comment]
Just released v1.3.1 which fixes this bug.

**Comment by pratikarya** [comment]
For some reason, I cannot find any update for version 1.3.1. The latest version, that Nuget shows is 1.3.0.

**Comment by SimonSimCity** [comment]
Sorry, forgot to submit it 🙈 Should be online in a second.
