### ISSUE TITLE
[Android] File download times out

### ISSUE THREAD

**Issue by stopiccot** [SimonSimCity/Xamarin-CrossDownloadManager#67]
```
DownloadManager: [1360] Stop requested with status HTTP_DATA_ERROR: Local halt requested; job probably timed out
```
It's kinda ironic that service designed for long background downloads times out. Any ways to workaround this?

**Comment by SimonSimCity** [comment]
How do you get this error? Haven't seen it before ...

The service you are using here is an native Android service. Could you please investigate if this error also occurs if you try to download the resource on native Android? If it also occurs when requesting a download of the resource in a native app, how to you (or others) handle it?

**Comment by stopiccot** [comment]
Sorry, can't share exact link - it's a private data. All I can tell that this is a ~100mb zip archive with mp3 files. It starts downloading but always fails between 80% and 90% of download on my connection. My guess is that native download manager kills all jobs that are taking too long to complete. Downloading same file using System.Net.Http.HttpClient works fine. Android version 7.0 device Nexus 5X.

**Comment by SimonSimCity** [comment]
Please analyze your network using a packet sniffer to see what really breaks it down. I can't see why a timeout should do it. I've been downloading stuff over Edge with this download-manager - sometimes for hours - and haven't had any problems so far.

Does it also break with other files? Maybe the server cuts down the connection after a certain time? Please analyze the bytes when it stops. Does it change? Can you try to throttle or to speed up your connection?

**Comment by SimonSimCity** [comment]
Closed due to lack of feedback.
