### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads

### ISSUE THREAD

**Issue by dashika** [SimonSimCity/Xamarin-CrossDownloadManager#82]
To help us fix your issue, please provide the information in the below template. 

### Steps to reproduce

I have problem with Android 4.3 Samsung S4 when try download file:
java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads

### Configuration

**Platform:** 

- [x] Android 4.3

**Device:** 
- [x] Real device (Samsung S4)

**Comment by dashika** [comment]
It was fail on my phone, was off download manager, this solution help me:

 try
            {
                //Open the specific App Info page:
                Intent intent = new Intent(Android.Provider.Settings.ActionApplicationDetailsSettings);
                intent.SetData(Android.Net.Uri.Parse("package:" + "com.android.providers.downloads"));
                StartActivity(intent);

            }
            catch (ActivityNotFoundException e)
            {
                //Open the generic Apps page:
                Intent intent = new Intent(Android.Provider.Settings.ActionManageApplicationsSettings );
               StartActivity(intent);
            }

**Comment by SimonSimCity** [comment]
@dashika this is nothing related to the code I wrote, do I understand that correctly ..?

**Comment by dashika** [comment]
Yes, you can add my fix in code, if you want, but in not neccesary. It need if download manager turn off.
If download manager turn off - and I try download something using your demo - happened java.lang.IllegalArgumentException.

**Comment by SimonSimCity** [comment]
Currently I don't really know where to put these lines ...

It would be a great help to me if you would have the chance to fork this repository, fix the bug in my sample project and create a pull request so I can have a closer look at where exactly this library needs the improvement and fix it for everyone.

**Comment by SimonSimCity** [comment]
@dashika You said that it also happens using my demo project. Could you please tell me more and provide me with an instruction to reproduce it?

**Comment by dashika** [comment]
Turn off Download Manager on Android - and run your demo after it.

**Comment by SimonSimCity** [comment]
Why would you stop a system-app and expect everything to work fine 😨

And what should I do against it? I could document it and the developers then have themselves to decide how to proceed - this is something I would accept ...

Please tell me what your solution is doing in detail. As far as I can see, you're just trying it once more without uri, which doesn't really help because the donwload manager has no idea of what to do.

**Comment by dashika** [comment]
It unusual situation - if you want you can decide it, no - close question =)) 
On my phone happened this situation - so I described you about it.   

I wrote code upper - Open setting for turn on download manager.

**Comment by SimonSimCity** [comment]
@dashika thanks for reporting. The only possibility I could reproduce this was by disabling the download-manager, which clearly is an intention that you want to stop using it. I'll add it to the documentation and let the developers handle it.

This library will not be affected by this after implementing #34. So if anyone has time and feels compelled, feel free to work on it after dropping a mail to me. I'll provide you with all the info I have.
