### ISSUE TITLE
[Android][iOS] Missing reference

### ISSUE THREAD

**Issue by pratikarya** [SimonSimCity/Xamarin-CrossDownloadManager#86]
I installed the Xam.Plugins.DownloadManager version 1.3.6 from Nuget.
But references to Plugin.DownloadManager.Android and Plugin.DownloadManager.iOS were missing.
Whereas, in your sample project, both Android and iOS, have the above respective references. 

I had earlier reported the following issue, which was resolved: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/issues/64

But there is a catch, I had tested it on your sample project, which had the reference to Plugin.DownloadManager.Android, because of which download canceling events were working. 
But when I tried it in my project it did not. So on further investigating, I found out, there was no reference to Plugin.DownloadManager.Android in my project. Adding the whole project itself in the solution itself, got it working.

So ideally, should there be a reference at all in the Nuget? Or am I missing something?

**Comment by SimonSimCity** [comment]
I don't know your project structure, but I guess you have three projects where one is for the shared code and two for the platform specific code - Android and iOS, right?

This package needs to be installed in any of these projects. By adding it to the shared project, you add the shared code of this library and by adding the package to the platform specific projects you add the actual implementation.

I lately found this video, which might help you getting started: https://www.youtube.com/watch?v=rcbm6R4e8jQ (credits to Rohit Arnav for recording)

**Comment by SimonSimCity** [comment]
Closed due to lack of feedback ...
