### ISSUE TITLE
Cancel Download; Show common progress; Image

### ISSUE THREAD

**Issue by AndreiMisiukevich** [SimonSimCity/Xamarin-CrossDownloadManager#87]
Hi
I've got several questions
1) How can user cancel downloading 
2) Is it possible to show common progress line (percentage). Because now it shows progress for each downloading item
3) Is it possible to set up custom image for notification

Thank you)

**Comment by AndreiMisiukevich** [comment]
Thanks for quick response.
1) I meant canceling downloading from Notification (But I understood, that it requires #34)
2) #34 
3) #34 

Yes, it's clear. I need to customize notification

**Comment by SimonSimCity** [comment]
Ok, let's continue on 1. a bit more. Which version of Android do you use? I guess we're only talking about Android here, right?

Out of this post (https://www.androidpolice.com/2016/03/21/android-n-feature-spotlight-the-download-managers-notification-gets-a-quickly-accessible-cancel-button/) it should be possible to do as of Android Nougat.

I just found this bug report: https://stackoverflow.com/questions/39231544/downloadmanager-and-android-7-0-cancel-feature

Could you please verify if it works on Android N?

**Comment by AndreiMisiukevich** [comment]
Yes, only about Android.
I tested it on Android 5.1

It's rather old) So, this feature is available starting 7.0, isn't it?
For old versions I should implement custom notification?

**Comment by SimonSimCity** [comment]
Yes, Android implemented it natively from Android 7.0 on. If you want to have it on earlier versions you'd have to implement a custom notification.

If you test this again with Android 7.0 or higher and you discover that it e.g. doesn't cancel the download properly please raise a new issue.

I'm closing this as a custom notification for 1. would be out of scope of this package.
