### ISSUE TITLE
Wifi only feature

### ISSUE THREAD

**Issue by JimmyPun610** [SimonSimCity/Xamarin-CrossDownloadManager#89]
I checked past issue and there is a setting to restrict the download action from mobile network. 
However I do not find it in nuget version 1.3.6 now. 
What will be the approach I need to do to achieve this function?

**Comment by SimonSimCity** [comment]
According to the changelog it was added in version 0.9.0 - and according to the nuget website, 1.3.6 is the latest release. Which version do you see if it's not 1.3.6?

An example of to use the restricting of mobile download is shown in the sample project: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/DownloadExample/Downloader.cs#L38

Does this answer the question already?

**Comment by JimmyPun610** [comment]
Got it. Thank you so much.
Is that a global settings or just affecting every single request?

**Comment by SimonSimCity** [comment]
It's available on `IDownloadManager.Start (file, mobileNetworkAllowed)` where `file` is of `IDownloadFile`. You call this method when you're done configuring your file and are ready to give it to the download manager which will start and manage the download. Hope that was clear 😅

Please be also aware of that the download manager himself can decide when to start the downloads. Adding them to the manager is just an indication that you are now done with your adjustments. The download manager might wait for a moment where it's e.g. less battery draining to download the file.

Feel free to close when your question is answered.

**Comment by JimmyPun610** [comment]
Thank you for answering my question!
