### ISSUE TITLE
Can't we download same link more than once with this plugin

### ISSUE THREAD

**Issue by anupk29** [SimonSimCity/Xamarin-CrossDownloadManager#92]
To help us fix your issue, please provide the information in the below template. 

> Note: If you want to save time, please create a fork, reproduce the bug in the sample projects and add a link to the repository here.

### Steps to reproduce

1.

2.

3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Configuration

**Platform:** 
- [x] iOS
- [x] Android
- [ ] UWP
- [ ] Other

**Device:** 
- [x] Simulator
- [x] Real device (please specify)

**Comment by anupk29** [comment]
i want to know how to download same link one than once and that file is not visible thru file explorer using this plugin

**Comment by anupk29** [comment]
not the same location which was stored previously.

**Comment by SimonSimCity** [comment]
@anupk29 please fork the repository and update the demo to reproduce this issue ... can't really see in code how this can happen.
